FROM docker.io/library/python:3.13-slim
RUN apt-get update && apt-get install -y --no-install-recommends iproute2 iw && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir certbot certbot-dns-cloudflare
WORKDIR /work
